"""
config/scenarios.py
-------------------
Stress scenarios: the single source of truth for every scenario in the project.

Each shock is a target peak deviation from the baseline forecast, in percentage
points, built up over `quarters` consecutive quarters of structural shocks.
Scenario paths are then generated by the BVAR's estimated dynamics.
"""
HORIZON = 12                 # quarters projected
CUMULATIVE_QUARTERS = 9      # standard stress-test horizon for cumulative losses

SCENARIOS = {
    "Baseline": {
        "description": "Model forecast with no shocks",
        "shocks": {},
    },
    "Adverse": {
        "description": "Moderate recession: unemployment +3 pp above baseline",
        "shocks": {"unemployment": {"peak": 3.0, "quarters": 4}},
    },
    "Severely Adverse": {
        "description": "Severe recession: unemployment +6 pp above baseline",
        "shocks": {"unemployment": {"peak": 6.0, "quarters": 4}},
    },
    "Stagflation": {
        "description": "Unemployment +3 pp and inflation +5 pp above baseline",
        "shocks": {"unemployment": {"peak": 3.0, "quarters": 4},
                   "inflation": {"peak": 5.0, "quarters": 4}},
    },
    "Sharp V-shaped (COVID-like)": {
        "description": "Sudden unemployment spike of +8 pp in a single quarter",
        "shocks": {"unemployment": {"peak": 8.0, "quarters": 1}},
    },
}
